{% set version = "0.9.4" %}

package:
  name: easyargs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/easyargs/easyargs-{{ version }}.tar.gz
  sha256: cc5638e2ca63183c9efb2b60d88c9ed1c1e338d41df45492dad078db4400aeb1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - six
  run:
    - python >={{ python_min }}
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - easyargs

about:
  home: https://github.com/stedmeister/easyargs
  license: MIT
  license_file: LICENSE.txt
  summary: Making argument parsing easy

extra:
  recipe-maintainers:
    - ocefpaf
