travis:
  secure:
    BINSTAR_TOKEN: ev8IxKNzyj9xiIYqvp3bhUIBWCXYbyXr/hxrcA0z3ClEb0gCgTI8w6pVoo7vohTXxBH5Yso/sETYVOt9vSEbPrZj5PIRA2FRWMvsG4VJ6y4vDJWkRCLyxKg2Xn7EdMdsMLIVAE3k8lPH2jHCoTE6UlB1nmhZgRjIgHi49AIbX5enLChTf1mu96qsCBFaqALCl/edq66M5cBE2Pmvbq0grm75sVGjoqd5VQP828JS5wLgfhYb8M1y+S5iBO8lbZiu6OBfgcJPxzu2XflQf0NexhJnmgRwOoQizIIS3HLaibMWjuj6aFDT5PbWSD2+2p9mESFTRRpBUdQhAwTtQhUtD3PqXFvfX3jtR5abyv2HTh+rHxuOJRA6XIgWXolfKTnJhYSKghVWinYq2hQKvdxDgvEYe5xur7nxiV1xBF3WGu4A+na9FcnHcdIAgorVRnnVgxUh8obEodMK/5cedIrbZsZjSs6cJs9812Lvdaw66lfIhHhI7kc0azSYXnUpVktKFtc5i+cy+wO4S94yQxzg62vDFz1tV/q544TsMfoIwZ95AWNky2H0pk/ViZJ61lMauEJn6AXdXfKSO61ZVFYGTUnuyt5woKXUTWPJgYW53OP2gtk7iaKvmKBDlhHAPOYkP7IWVVqdbgOYAaF5fo7TUC0vym78fupQF65JTGxnCKo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
