travis:
  secure:
    BINSTAR_TOKEN: DzAa+wwahkODMQ7/iAUILFjpB8iqhlFq7GpFm0Wp32pwb4birW5iC0+g6ZbKbwRZbl2MM+zsj+fLWcK0F59vEafsa955585PCYfckZE6yQtz3p3rlhMO4gjfxLBOyUwZNoVTtk63inSX4TSwK0c9U6cLJWGdDQtzhXHyLqf/FIlUFEimhfuP8/Z1e5fY6P236r/CYWOaqjZQ2LBklJapP4yjQmtR4iGQJiBW+MUX1vwe6XsdKOrUMRy2HBZXqX31bH3uGeL+g7z9cNuMsUal3D9QAZW+z4nR8dAfMeOcuo5b3JhIv21Vgzvdn8DDoOmgiHU6y3QNsaGO1dB1XZ2TuY94sp6XBOHRY+lfJgnn1voUSDRFqPamdWZEXSzOwcNU2J0NoAYX5g6jJSHd201SvgnKkzZ2OJHj2KXZL/VJaqNDGRylUOizT4CyVSgYbENfW/96LcDb6fN28xUBOdFdZ3kBTFKm4Mol8G7jRmZ//8vgxHsLJgDToExz4qc+YQJ0ZCXdDloAeSYTxtpsKjeSeKJJXt3gA8dFL9cXUx31iO+wEhvBz895sOWPLCw3B6zgMn1WnvsAGq41UYLAUyMTWGu0aM86XPc6e2ybDVUViHJywNDTbLrIYiru34wMNmbsxEGPP8/wmQ5qIkZWg/jqlsPq613N1cGsAMF1IZT/AjY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
